// MathML esperado de las fórmulas de pruebas/ejemplos-mate.ts, más unas cuantas de forma (HU-083). Lo importa
// src/lib/contenido/dorados.test.ts.
//
// Estas cadenas NO salen del código de este repo: se sacaron una sola vez del prototipo (dvarela5101/Calibra, index.html, blob
// b3f266a, último commit d1b2e6b del 22-sep-2026). Se abrió en Chromium y se serializó (`div.innerHTML`) lo que dibuja
// `window.__calibraMate.matematica("$fuente$")`. Sirven para que un cambio en las tablas de símbolos o en la forma del MathML
// (un `\le` que dibuje ≥, un `msubsup` que pase a `msub`, un `\sqrt{x}` con índice) rompa `npm test`: los ejemplos de
// ejemplos-mate.ts solo comprueban que no queden barras ni llaves.
//
// El dibujo de este repo agrega un `aria-label` a cada `<math>` (src/lib/contenido/leer.ts) y la prueba lo quita antes de
// comparar. Donde el dibujo se aparta a propósito del prototipo (el signo de un número, las barras `|` emparejadas, los espacios
// de borde de un `\text`) no hay dorado aquí: lo fijan los casos de src/lib/contenido/mate.test.ts. Si se cambia un ejemplo de
// ejemplos-mate.ts, el dorado de ese comando se vuelve a sacar del prototipo, no de este código.

/** Por comando: el MathML de `EJEMPLO_POR_COMANDO[comando]`. La clave del espacio fino es la coma. */
export const DORADO_POR_COMANDO: Readonly<Record<string, string>> = {
  frac: "<math><mfrac><mi>a</mi><mi>b</mi></mfrac></math>",
  sqrt: "<math><msqrt><mi>x</mi></msqrt></math>",
  int: "<math><msubsup><mo>∫</mo><mn>0</mn><mn>1</mn></msubsup><mi>x</mi></math>",
  iint: "<math><msub><mo>∬</mo><mi>D</mi></msub><mi>f</mi></math>",
  oint: "<math><msub><mo>∮</mo><mi>C</mi></msub><mi>f</mi></math>",
  sum: '<math><munderover><mo movablelimits="true">∑</mo><mrow><mi>n</mi><mo>=</mo><mn>1</mn></mrow><mi>∞</mi></munderover><msub><mi>a</mi><mi>n</mi></msub></math>',
  prod: '<math><munderover><mo movablelimits="true">∏</mo><mrow><mi>k</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover><mi>k</mi></math>',
  lim: '<math><munder><mo movablelimits="true">lim</mo><mrow><mi>x</mi><mo>→</mo><mn>0</mn></mrow></munder><mi>f</mi><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo></math>',
  left: '<math><mrow><mo stretchy="true" fence="true">(</mo><mi>x</mi><mo stretchy="true" fence="true">)</mo></mrow></math>',
  right: '<math><mrow><mo stretchy="true" fence="true">[</mo><mi>x</mi><mo stretchy="true" fence="true">]</mo></mrow></math>',
  text: "<math><mi>a</mi><mtext>si</mtext><mi>b</mi></math>",
  vec: '<math><mover accent="true"><mi>v</mi><mo>→</mo></mover></math>',
  bar: '<math><mover accent="true"><mi>x</mi><mo>¯</mo></mover></math>',
  hat: '<math><mover accent="true"><mi>x</mi><mo>^</mo></mover></math>',
  mathrm: '<math><mi mathvariant="normal">d</mi><mi>x</mi></math>',
  sen: '<math><mi mathvariant="normal">sen</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  sin: '<math><mi mathvariant="normal">sin</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  cos: '<math><mi mathvariant="normal">cos</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  tan: '<math><mi mathvariant="normal">tan</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  sec: '<math><mi mathvariant="normal">sec</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  csc: '<math><mi mathvariant="normal">csc</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  cot: '<math><mi mathvariant="normal">cot</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  ln: '<math><mi mathvariant="normal">ln</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  log: '<math><mi mathvariant="normal">log</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  exp: '<math><mi mathvariant="normal">exp</mi><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></math>',
  alpha: "<math><mi>α</mi></math>",
  beta: "<math><mi>β</mi></math>",
  gamma: "<math><mi>γ</mi></math>",
  delta: "<math><mi>δ</mi></math>",
  epsilon: "<math><mi>ϵ</mi></math>",
  varepsilon: "<math><mi>ε</mi></math>",
  theta: "<math><mi>θ</mi></math>",
  lambda: "<math><mi>λ</mi></math>",
  mu: "<math><mi>μ</mi></math>",
  nu: "<math><mi>ν</mi></math>",
  pi: "<math><mi>π</mi></math>",
  rho: "<math><mi>ρ</mi></math>",
  sigma: "<math><mi>σ</mi></math>",
  tau: "<math><mi>τ</mi></math>",
  phi: "<math><mi>ϕ</mi></math>",
  varphi: "<math><mi>φ</mi></math>",
  omega: "<math><mi>ω</mi></math>",
  Delta: '<math><mi mathvariant="normal">Δ</mi><mi>x</mi></math>',
  Sigma: '<math><mi mathvariant="normal">Σ</mi></math>',
  Omega: '<math><mi mathvariant="normal">Ω</mi></math>',
  Gamma: '<math><mi mathvariant="normal">Γ</mi></math>',
  Phi: '<math><mi mathvariant="normal">Φ</mi></math>',
  le: "<math><mi>a</mi><mo>≤</mo><mi>b</mi></math>",
  leq: "<math><mi>a</mi><mo>≤</mo><mi>b</mi></math>",
  ge: "<math><mi>a</mi><mo>≥</mo><mi>b</mi></math>",
  geq: "<math><mi>a</mi><mo>≥</mo><mi>b</mi></math>",
  ne: "<math><mi>a</mi><mo>≠</mo><mi>b</mi></math>",
  neq: "<math><mi>a</mi><mo>≠</mo><mi>b</mi></math>",
  approx: "<math><mi>a</mi><mo>≈</mo><mi>b</mi></math>",
  pm: "<math><mi>a</mi><mo>±</mo><mi>b</mi></math>",
  mp: "<math><mi>a</mi><mo>∓</mo><mi>b</mi></math>",
  to: "<math><mi>x</mi><mo>→</mo><mn>0</mn></math>",
  rightarrow: "<math><mi>x</mi><mo>→</mo><mn>0</mn></math>",
  infty: "<math><mi>∞</mi></math>",
  cdot: "<math><mi>a</mi><mo>·</mo><mi>b</mi></math>",
  times: "<math><mi>a</mi><mo>×</mo><mi>b</mi></math>",
  div: "<math><mi>a</mi><mo>÷</mo><mi>b</mi></math>",
  partial: "<math><mi>∂</mi><mi>x</mi></math>",
  nabla: "<math><mi>∇</mi><mi>f</mi></math>",
  ",": '<math><mi>a</mi><mspace width="0.1667em"></mspace><mi>b</mi></math>',
  ";": '<math><mi>a</mi><mspace width="0.2778em"></mspace><mi>b</mi></math>',
  quad: '<math><mi>a</mi><mspace width="1em"></mspace><mi>b</mi></math>',
};

export const DORADOS_ANIDADOS: readonly (readonly [string, string])[] = [
  [String.raw`x_{i_j}`, "<math><msub><mi>x</mi><msub><mi>i</mi><mi>j</mi></msub></msub></math>"],
  [String.raw`x_{a_{b_{c_d}}}`, "<math><msub><mi>x</mi><msub><mi>a</mi><msub><mi>b</mi><msub><mi>c</mi><mi>d</mi></msub></msub></msub></msub></math>"],
  [String.raw`\frac{\frac{1}{2}}{3}`, "<math><mfrac><mfrac><mn>1</mn><mn>2</mn></mfrac><mn>3</mn></mfrac></math>"],
  [String.raw`\frac{1}{1 + \frac{1}{1 + \frac{1}{x}}}`, "<math><mfrac><mn>1</mn><mrow><mn>1</mn><mo>+</mo><mfrac><mn>1</mn><mrow><mn>1</mn><mo>+</mo><mfrac><mn>1</mn><mi>x</mi></mfrac></mrow></mfrac></mrow></mfrac></math>"],
  [String.raw`\sqrt[3]{x^{2}}`, "<math><mroot><msup><mi>x</mi><mn>2</mn></msup><mn>3</mn></mroot></math>"],
  [String.raw`\sqrt{\frac{a_n}{b_n}}`, "<math><msqrt><mfrac><msub><mi>a</mi><mi>n</mi></msub><msub><mi>b</mi><mi>n</mi></msub></mfrac></msqrt></math>"],
  [String.raw`a_{n+1}^{2}`, "<math><msubsup><mi>a</mi><mrow><mi>n</mi><mo>+</mo><mn>1</mn></mrow><mn>2</mn></msubsup></math>"],
  [String.raw`\sum_{n=1}^{\infty}\frac{1}{n^2}`, '<math><munderover><mo movablelimits="true">∑</mo><mrow><mi>n</mi><mo>=</mo><mn>1</mn></mrow><mi>∞</mi></munderover><mfrac><mn>1</mn><msup><mi>n</mi><mn>2</mn></msup></mfrac></math>'],
  [String.raw`\int_{a_1}^{b^2} \frac{f(x)}{g_{k}(x)}\,dx`, '<math><msubsup><mo>∫</mo><msub><mi>a</mi><mn>1</mn></msub><msup><mi>b</mi><mn>2</mn></msup></msubsup><mfrac><mrow><mi>f</mi><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo></mrow><mrow><msub><mi>g</mi><mi>k</mi></msub><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo></mrow></mfrac><mspace width="0.1667em"></mspace><mi>d</mi><mi>x</mi></math>'],
  [String.raw`\lim_{x_0 \to \infty} \frac{\sen^2 x}{x_0^{2}}`, '<math><munder><mo movablelimits="true">lim</mo><mrow><msub><mi>x</mi><mn>0</mn></msub><mo>→</mo><mi>∞</mi></mrow></munder><mfrac><mrow><msup><mi mathvariant="normal">sen</mi><mn>2</mn></msup><mo lspace="0" rspace="0.1667em">\u2061</mo><mi>x</mi></mrow><msubsup><mi>x</mi><mn>0</mn><mn>2</mn></msubsup></mfrac></math>'],
  [String.raw`\left( \frac{a_i}{b_i} \right)^{2}`, '<math><msup><mrow><mo stretchy="true" fence="true">(</mo><mfrac><msub><mi>a</mi><mi>i</mi></msub><msub><mi>b</mi><mi>i</mi></msub></mfrac><mo stretchy="true" fence="true">)</mo></mrow><mn>2</mn></msup></math>'],
  [String.raw`e^{-\frac{x^{2}}{2}}`, "<math><msup><mi>e</mi><mrow><mo>−</mo><mfrac><msup><mi>x</mi><mn>2</mn></msup><mn>2</mn></mfrac></mrow></msup></math>"],
];

export const DORADOS_EXTRA: readonly (readonly [string, string])[] = [
  [String.raw`x_a^b`, "<math><msubsup><mi>x</mi><mi>a</mi><mi>b</mi></msubsup></math>"],
  [String.raw`x_i^2`, "<math><msubsup><mi>x</mi><mi>i</mi><mn>2</mn></msubsup></math>"],
  [String.raw`x^a_b`, "<math><msubsup><mi>x</mi><mi>b</mi><mi>a</mi></msubsup></math>"],
  [String.raw`\sqrt[n]{x}`, "<math><mroot><mi>x</mi><mi>n</mi></mroot></math>"],
  [String.raw`\sqrt{x+1}`, "<math><msqrt><mrow><mi>x</mi><mo>+</mo><mn>1</mn></mrow></msqrt></math>"],
  [String.raw`\iint_D f\,dA`, '<math><msub><mo>∬</mo><mi>D</mi></msub><mi>f</mi><mspace width="0.1667em"></mspace><mi>d</mi><mi>A</mi></math>'],
  [String.raw`\oint_C \vec{F} \cdot d\vec{r}`, '<math><msub><mo>∮</mo><mi>C</mi></msub><mover accent="true"><mi>F</mi><mo>→</mo></mover><mo>·</mo><mi>d</mi><mover accent="true"><mi>r</mi><mo>→</mo></mover></math>'],
  [String.raw`\left[ x \right]`, '<math><mrow><mo stretchy="true" fence="true">[</mo><mi>x</mi><mo stretchy="true" fence="true">]</mo></mrow></math>'],
  [String.raw`\left| x \right|`, '<math><mrow><mo stretchy="true" fence="true">|</mo><mi>x</mi><mo stretchy="true" fence="true">|</mo></mrow></math>'],
  [String.raw`\left. \frac{df}{dx} \right|_{x=0}`, '<math><msub><mrow><mfrac><mrow><mi>d</mi><mi>f</mi></mrow><mrow><mi>d</mi><mi>x</mi></mrow></mfrac><mo stretchy="true" fence="true">|</mo></mrow><mrow><mi>x</mi><mo>=</mo><mn>0</mn></mrow></msub></math>'],
  [String.raw`\bar{x}`, '<math><mover accent="true"><mi>x</mi><mo>¯</mo></mover></math>'],
  [String.raw`\hat{x}`, '<math><mover accent="true"><mi>x</mi><mo>^</mo></mover></math>'],
  [String.raw`\bar{AB}`, '<math><mover accent="true"><mrow><mi>A</mi><mi>B</mi></mrow><mo>¯</mo></mover></math>'],
  [String.raw`[a, b]`, '<math><mo stretchy="false">[</mo><mi>a</mi><mo>,</mo><mi>b</mi><mo stretchy="false">]</mo></math>'],
  [String.raw`(a, b)`, '<math><mo stretchy="false">(</mo><mi>a</mi><mo>,</mo><mi>b</mi><mo stretchy="false">)</mo></math>'],
  [String.raw`|x|`, '<math><mo stretchy="false">|</mo><mi>x</mi><mo stretchy="false">|</mo></math>'],
  [String.raw`(a)`, '<math><mo stretchy="false">(</mo><mi>a</mi><mo stretchy="false">)</mo></math>'],
  [String.raw`[x]`, '<math><mo stretchy="false">[</mo><mi>x</mi><mo stretchy="false">]</mo></math>'],
  [String.raw`a/b`, '<math><mi>a</mi><mo lspace="0" rspace="0">/</mo><mi>b</mi></math>'],
  [String.raw`f'(x)`, '<math><mi>f</mi><mo>′</mo><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo></math>'],
  [String.raw`n!`, "<math><mi>n</mi><mo>!</mo></math>"],
  [String.raw`a * b`, "<math><mi>a</mi><mo>*</mo><mi>b</mi></math>"],
  [String.raw`x < y > z`, "<math><mi>x</mi><mo>&lt;</mo><mi>y</mi><mo>&gt;</mo><mi>z</mi></math>"],
  [String.raw`a : b ; c`, "<math><mi>a</mi><mo>:</mo><mi>b</mi><mo>;</mo><mi>c</mi></math>"],
  [String.raw`a . b`, "<math><mi>a</mi><mo>.</mo><mi>b</mi></math>"],
  [String.raw`\phi + \varphi`, "<math><mi>ϕ</mi><mo>+</mo><mi>φ</mi></math>"],
  [String.raw`\epsilon + \varepsilon`, "<math><mi>ϵ</mi><mo>+</mo><mi>ε</mi></math>"],
  [String.raw`\int_{-\infty}^{\infty} e^{-x^2}\,dx`, '<math><msubsup><mo>∫</mo><mrow><mo>−</mo><mi>∞</mi></mrow><mi>∞</mi></msubsup><msup><mi>e</mi><mrow><mo>−</mo><msup><mi>x</mi><mn>2</mn></msup></mrow></msup><mspace width="0.1667em"></mspace><mi>d</mi><mi>x</mi></math>'],
  [String.raw`\prod_{k=1}^{n} (1 + x_k)`, '<math><munderover><mo movablelimits="true">∏</mo><mrow><mi>k</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover><mo stretchy="false">(</mo><mn>1</mn><mo>+</mo><msub><mi>x</mi><mi>k</mi></msub><mo stretchy="false">)</mo></math>'],
  [String.raw`\lim_{n \to \infty} \left(1 + \frac{1}{n}\right)^n`, '<math><munder><mo movablelimits="true">lim</mo><mrow><mi>n</mi><mo>→</mo><mi>∞</mi></mrow></munder><msup><mrow><mo stretchy="true" fence="true">(</mo><mrow><mn>1</mn><mo>+</mo><mfrac><mn>1</mn><mi>n</mi></mfrac></mrow><mo stretchy="true" fence="true">)</mo></mrow><mi>n</mi></msup></math>'],
  [String.raw`\sum_{i=1}^{n} i = \frac{n(n+1)}{2}`, '<math><munderover><mo movablelimits="true">∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover><mi>i</mi><mo>=</mo><mfrac><mrow><mi>n</mi><mo stretchy="false">(</mo><mi>n</mi><mo>+</mo><mn>1</mn><mo stretchy="false">)</mo></mrow><mn>2</mn></mfrac></math>'],
];
